[VPP] Fix MFXVideoVPP_Init vpp deinterlacing
Error: MFXVideoVPP_Init(session, par):
CHECK STATUS(expected MFX_ERR_INVALID_VIDEO_PARAM(0xfffffff1)):
MFX_ERR_UNSUPPORTED(0xfffffffd)
Error appeared in the test case 8 (FOURCC = Y210,
Deinterlacing.Mode = MFX_DEINTERLACING_ADVANCED_SCD)
on all platforms when GEN11 defined.
Exact problem was in the no checks for actual platform, which is used.
For fix such check has been added into the function CheckFrameInfo().
This function's signature and calls have been modified accordingly.

Issue: MDP-35135
Test: beh_vpp_deinterlacing

Change-Id: Iac7b72757dd0900f3208e88d2891e68cef844777