Fix compile error in mfx_player/mfx_serializer
Similar fix as commit 60e10eb2b1a556fca384c...

error: switch condition has type bool [-Werror=switch-bool]

Remove the switch statement and use a simpler and equivalent approach.
This also fixes the warning/error.

Change-Id: Ibf8674d6a3460bfe113bc916efffac779e27bfd0
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>