ci: support clang-12 and fix errors and warnings (#1997)
* build: fix clang-12 build error

Test: build
Issue: oneapi-src/oneVPL-intel-gpu#6

_studio/shared/include/libmfx_allocator.h:642:65: error: copying member subobject of type 'std::atomic<size_t>' (aka 'atomic<unsigned long>') invokes deleted constructor

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

* build: fix clang-12 -Winconsistent-missing-override warning

Test: build
Issue: oneapi-src/oneVPL-intel-gpu#6

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

* build: fix clang-12 -Wmissing-braces warning

Test: build
Issue: oneapi-src/oneVPL-intel-gpu#6

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

* build: comply with cmake-3.14 declared requirement

Test: build
Issue: no

CMP0092 first appeared in cmake-3.15

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

Co-authored-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>