[sample_encode,smt] Add BitrateLimit to cmd line options (backmerge)
-Added -BitrateLimit:<on,off> option to sample_encode and smt command line
 options. BitrateLimit equals MFX_CODINGOPTION_OFF by default on sample side.
-Added warning to sample_encode and smt in case
 when BitrateLimit is ON and bitrate was changed.
-Updated mediasdk, sample_encode and smt docs.
-+ Some smt parse parameters alignment with OS to prevent
 too many chained else-if clauses (compiler error C1061).

Issue: VSMGWL-24903
Test: 4k 60fps encode/transcode
Github: f37ff61f

Change-Id: I46c00cbd63f7677b2a59b210d6253e3c7da7da07