MSVC 2015 fixed error C3688: invalid literal suffix 'L'; literal operator or literal operator template 'operator ""L' not found
string literals like  L""L"" now causes this problem because ""L is compiled as 'user defined suffix'
refer to User-defined literals (since C++11) http://en.cppreference.com/w/cpp/language/user_literal

Change-Id: I569e7c41c97ced3ca8c829b156259261b2a8eeda
Signed-off-by: Sergey Solodkov <Sergey.Solodkov@intel.com>