[ASC] Add missing header after d978f4ece795
_studio/shared/asc/src/asc.cpp:1129:26: error: no member named 'log' in namespace 'std'
    result = ((c1 * std::log(x)) + c0) >= y;
                    ~~~~~^

Issue: -
Test: -
Github: de86cd1 ([ASC] Add missing header after d978f4ece795)

Change-Id: I01e7347bb8602cef50ffb16f6281d56bac1069af