fix compile error in mfx_serializer
Since commit e15d4f8bf967aea9e98de7a287cd93cbcf104638, all warnings
are treated as errors (-Werror).
With GCC 5.x, a warning is generated for "switch-bool" and treated
as an error:

mfx_serializer.cpp:872:23: error: switch condition has type bool
  [-Werror=switch-bool]

Remove the switch statement and use a simpler and equivalent approach.
This also fixes the warning/error.

Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>